export class EditorConfig {
  static getEditorOptions(theme) {
    return {
      theme: theme,
      automaticLayout: true,
      renderSideBySide: true,
      renderWhitespace: 'selection',
      scrollBeyondLastLine: true,
      minimap: { enabled: true },
      fontSize: 14,
      fontFamily: 'Consolas, "Courier New", monospace',
      lineNumbers: 'on',
      glyphMargin: true,
      folding: true,
      lineDecorationsWidth: 10,
      lineNumbersMinChars: 5,
      renderLineHighlight: 'all',
      scrollbar: {
        vertical: 'visible',
        horizontal: 'visible',
        useShadows: false,
        verticalHasArrows: false,
        horizontalHasArrows: false,
        verticalScrollbarSize: 10,
        horizontalScrollbarSize: 10,
        arrowSize: 30
      },
      overviewRulerLanes: 3,
      overviewRulerBorder: false,
      mouseWheelZoom: true,
      cursorBlinking: 'blink',
      cursorSmoothCaretAnimation: true,
      smoothScrolling: true,
      contextmenu: true,
      enableSplitViewResizing: true,
      renderSideBySideInlineBreakpoint: 900,
      useInlineViewWhenSpaceIsLimited: true,
      // Disable built-in language features that conflict with LSP
      quickSuggestions: false,
      parameterHints: { enabled: false },
      suggestOnTriggerCharacters: false,
      acceptSuggestionOnEnter: 'off',
      tabCompletion: 'off',
      wordBasedSuggestions: false,
      hover: { enabled: false },
      occurrencesHighlight: false,
      selectionHighlight: false,
      renderValidationDecorations: 'off',
      links: false,
      // Keep features that don't conflict
      formatOnPaste: false,
      formatOnType: false,
      autoClosingBrackets: 'languageDefined',
      autoClosingQuotes: 'languageDefined',
      autoSurround: 'languageDefined',
      autoIndent: 'full',
      // Diff editor specific options
      enableSplitViewResizing: true,
      renderMarginRevertIcon: true,
      renderIndicators: true,
      renderOverviewRuler: true,
      diffCodeLens: true,
      ignoreTrimWhitespace: false,
      originalEditable: false  // Original side is always read-only
    };
  }
}
