export class EditorConfig {
  static getEditorOptions(theme) {
    return {
      theme: theme,
      automaticLayout: true,
      renderSideBySide: true,
      renderWhitespace: 'selection',
      scrollBeyondLastLine: true,
      minimap: { enabled: true },
      fontSize: 14,
      fontFamily: 'Consolas, "Courier New", monospace',
      lineNumbers: 'on',
      folding: true,
      scrollbar: {
        vertical: 'visible',
        horizontal: 'visible',
        verticalScrollbarSize: 10,
        horizontalScrollbarSize: 10
      },
      // Enable inline diff decorations and revert icons
      enableSplitViewResizing: true,
      renderMarginRevertIcon: true,
      renderIndicators: true,
      renderOverviewRuler: true,
      diffCodeLens: true,
      ignoreTrimWhitespace: false,
      renderLineHighlight: 'all',
      renderValidationDecorations: 'on',
      showFoldingControls: 'always',
      glyphMargin: true,
      contextmenu: true,
      mouseWheelZoom: true,
      suggestOnTriggerCharacters: true,
      acceptSuggestionOnEnter: 'on',
      accessibilitySupport: 'auto',
      autoIndent: 'full',
      formatOnPaste: false,
      formatOnType: false,
      renderControlCharacters: false,
      renderIndentGuides: true,
      renderLineHighlightOnlyWhenFocus: false,
      revealHorizontalRightPadding: 30,
      roundedSelection: true,
      selectOnLineNumbers: true,
      selectionHighlight: true,
      showUnused: true,
      smoothScrolling: false,
      snippetSuggestions: 'inline',
      tabCompletion: 'on',
      useTabStops: true,
      wordWrap: 'off',
      wordWrapBreakAfterCharacters: '\t})]?|/&,;',
      wordWrapBreakBeforeCharacters: '([{',
      wrappingIndent: 'none',
      wrappingStrategy: 'simple',
      originalEditable: false  // Original side is always read-only
    };
  }
}
